FROM python:3.11-slim
WORKDIR /app
COPY python-workers/genai-worker/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY python-workers/genai-worker ./genai-worker
WORKDIR /app/genai-worker
CMD ["python", "main.py"]
