FROM python:3.11-slim
WORKDIR /app
COPY python-workers/analyzer-frida/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY python-workers/analyzer-frida ./analyzer-frida
WORKDIR /app/analyzer-frida
CMD ["python", "main.py"]
